### ISSUE TITLE
Server crashes when trying to execute SELECT agtype_to_int4(bool('true'));

### ISSUE THREAD

**Issue by saygoodbyye** [apache/age#1329]
**Describe the bug**
Server crashes when executing the following SQL-script

**How are you accessing AGE (Command line, driver, etc.)?**
Accessing AGE through command line.

**What data setup do we need to do?**
Apache AGE (master branch) with PostgreSQL (REL_15_STABLE).

**What is the necessary configuration info needed?**
My PostgreSQL configuration:
```
./configure CFLAGS=" -Og" --enable-tap-tests --enable-debug --enable-cassert
```

**What is the command that caused the error?**
```pgsql
CREATE EXTENSION age;
SET search_path TO ag_catalog;
SELECT agtype_to_int4(bool('true'));
```
backtrace:
```
#0  pg_detoast_datum (datum=0x1) at fmgr.c:1710
#1  0x00007efc8e868800 in agtype_to_int4 (fcinfo=0x55c95d67bf18) at src/backend/utils/adt/agtype.c:2661
#2  0x000055c95bd56255 in ExecInterpExpr (state=0x55c95d67be28, econtext=0x55c95d67c058, isnull=0x7ffd6f65f1d4) at execExprInterp.c:751
#3  0x000055c95bd52f8e in ExecInterpExprStillValid (state=0x55c95d67be28, econtext=0x55c95d67c058, isNull=0x7ffd6f65f1d4) at execExprInterp.c:1826
#4  0x000055c95be38e8c in ExecEvalExprSwitchContext (isNull=0x7ffd6f65f1d4, econtext=<optimized out>, state=0x55c95d67be28) at ../../../../src/include/executor/executor.h:344
#5  evaluate_expr (expr=<optimized out>, result_type=result_type@entry=23, result_typmod=result_typmod@entry=-1, result_collation=result_collation@entry=0) at clauses.c:4823
#6  0x000055c95be39068 in evaluate_function (funcid=funcid@entry=16848, result_type=result_type@entry=23, result_typmod=result_typmod@entry=-1, result_collid=result_collid@entry=0, input_collid=input_collid@entry=0, args=args@entry=0x55c95d5e4dd0, 
    funcvariadic=false, func_tuple=0x7efc8e8d9460, context=0x7ffd6f65f5c0) at clauses.c:4325
#7  0x000055c95be3b0f3 in simplify_function (funcid=16848, result_type=23, result_typmod=-1, result_collid=result_collid@entry=0, input_collid=input_collid@entry=0, args_p=args_p@entry=0x7ffd6f65f3c0, funcvariadic=false, process_args=true, 
    allow_non_const=true, context=0x7ffd6f65f5c0) at clauses.c:3908
#8  0x000055c95be3932c in eval_const_expressions_mutator (node=0x55c95d51abe8, context=0x7ffd6f65f5c0) at clauses.c:2427
#9  0x000055c95bdd0384 in expression_tree_mutator (node=node@entry=0x55c95d51ad58, mutator=mutator@entry=0x55c95be390aa <eval_const_expressions_mutator>, context=context@entry=0x7ffd6f65f5c0) at nodeFuncs.c:3080
#10 0x000055c95be3a566 in eval_const_expressions_mutator (node=0x55c95d51ad58, context=0x7ffd6f65f5c0) at clauses.c:3527
#11 0x000055c95bdd05ce in expression_tree_mutator (node=node@entry=0x55c95d51adb0, mutator=mutator@entry=0x55c95be390aa <eval_const_expressions_mutator>, context=context@entry=0x7ffd6f65f5c0) at nodeFuncs.c:3166
#12 0x000055c95be3a566 in eval_const_expressions_mutator (node=0x55c95d51adb0, context=context@entry=0x7ffd6f65f5c0) at clauses.c:3527
#13 0x000055c95be3a6ca in eval_const_expressions (root=root@entry=0x55c95d5e4800, node=<optimized out>) at clauses.c:2107
#14 0x000055c95be1bcfc in preprocess_expression (root=root@entry=0x55c95d5e4800, expr=<optimized out>, kind=kind@entry=1) at planner.c:1127
#15 0x000055c95be2369d in subquery_planner (glob=glob@entry=0x55c95d51a690, parse=parse@entry=0x55c95d51a140, parent_root=parent_root@entry=0x0, hasRecursion=hasRecursion@entry=false, tuple_fraction=tuple_fraction@entry=0) at planner.c:792
#16 0x000055c95be24280 in standard_planner (parse=0x55c95d51a140, query_string=<optimized out>, cursorOptions=2048, boundParams=<optimized out>) at planner.c:408
#17 0x000055c95be24838 in planner (parse=parse@entry=0x55c95d51a140, query_string=query_string@entry=0x55c95d519090 "SELECT agtype_to_int4(bool('true'));", cursorOptions=cursorOptions@entry=2048, boundParams=boundParams@entry=0x0) at planner.c:277
#18 0x000055c95bf00406 in pg_plan_query (querytree=querytree@entry=0x55c95d51a140, query_string=query_string@entry=0x55c95d519090 "SELECT agtype_to_int4(bool('true'));", cursorOptions=cursorOptions@entry=2048, boundParams=boundParams@entry=0x0)
    at postgres.c:883
#19 0x000055c95bf004c3 in pg_plan_queries (querytrees=0x55c95d51ae98, query_string=query_string@entry=0x55c95d519090 "SELECT agtype_to_int4(bool('true'));", cursorOptions=cursorOptions@entry=2048, boundParams=boundParams@entry=0x0) at postgres.c:975
#20 0x000055c95bf00923 in exec_simple_query (query_string=query_string@entry=0x55c95d519090 "SELECT agtype_to_int4(bool('true'));") at postgres.c:1169
#21 0x000055c95bf02870 in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4598
#22 0x000055c95be67851 in BackendRun (port=port@entry=0x55c95d53a110) at postmaster.c:4514
#23 0x000055c95be69861 in BackendStartup (port=port@entry=0x55c95d53a110) at postmaster.c:4242
#24 0x000055c95be69a9a in ServerLoop () at postmaster.c:1809
#25 0x000055c95be6b06f in PostmasterMain (argc=argc@entry=3, argv=argv@entry=0x55c95d5135a0) at postmaster.c:1481
#26 0x000055c95bdb7dd7 in main (argc=3, argv=0x55c95d5135a0) at main.c:202
```

**Expected behavior**
Expected ERROR to be shown or sql query to be succesfully executed

**Comment by jrgemignani** [comment]
Looking into this one.

**Comment by jrgemignani** [comment]
Created PR #1339 to address this.

**Comment by jrgemignani** [comment]
@saygoodbyye This should be corrected now. Please verify and if satisfied, close the issue.

**Comment by saygoodbyye** [comment]
Thank you!
