### ISSUE TITLE
Server crashes when executing SELECT agtype_build_map('null'::agtype, 1); 

### ISSUE THREAD

**Issue by saygoodbyye** [apache/age#1956]
Describe the bug
Server crashes when executing the following SQL-script

How are you accessing AGE (Command line, driver, etc.)?
Accessing AGE through command line.

What data setup do we need to do?
Apache AGE (PG16 branch) with PostgreSQL (REL_16_STABLE).

What is the necessary configuration info needed?
My PostgreSQL configuration:
```
./configure CFLAGS=" -Og" --enable-tap-tests --enable-debug --enable-cassert
```
What is the command that caused the error?
```sql
CREATE EXTENSION age;
SET search_path TO ag_catalog;
SELECT agtype_build_map('null'::agtype, 1);
```
backtrace:
```c
#0  push_agtype_value_scalar (pstate=pstate@entry=0x7fff3cb4e5d0, seq=<optimized out>, scalar_val=0x0) at src/backend/utils/adt/agtype_util.c:732
#1  0x00007553a61c116f in push_agtype_value (pstate=pstate@entry=0x7fff3cb4e5d0, seq=seq@entry=WAGT_KEY, agtval=agtval@entry=0x0) at src/backend/utils/adt/agtype_util.c:672
#2  0x00007553a61a9817 in agtype_build_map_as_agtype_value (fcinfo=fcinfo@entry=0x620b50c51f38) at src/backend/utils/adt/agtype.c:2413
#3  0x00007553a61aa16f in agtype_build_map (fcinfo=0x620b50c51f38) at src/backend/utils/adt/agtype.c:2440
#4  0x0000620b4f62a6fe in ExecInterpExpr (state=0x620b50c51e58, econtext=0x620b50c52068, isnull=0x7fff3cb4e6e4) at execExprInterp.c:734
#5  0x0000620b4f627230 in ExecInterpExprStillValid (state=0x620b50c51e58, econtext=0x620b50c52068, isNull=0x7fff3cb4e6e4) at execExprInterp.c:1870
#6  0x0000620b4f736ef4 in ExecEvalExprSwitchContext (isNull=0x7fff3cb4e6e4, econtext=<optimized out>, state=0x620b50c51e58) at ../../../../src/include/executor/executor.h:355
#7  evaluate_expr (expr=<optimized out>, result_type=result_type@entry=41028, result_typmod=result_typmod@entry=-1, result_collation=result_collation@entry=0) at clauses.c:4979
#8  0x0000620b4f7370d0 in evaluate_function (funcid=funcid@entry=41412, result_type=result_type@entry=41028, result_typmod=result_typmod@entry=-1, result_collid=result_collid@entry=0, input_collid=input_collid@entry=0, args=args@entry=0x620b50c50500,
    funcvariadic=false, func_tuple=0x7553a65dac80, context=0x7fff3cb4ead0) at clauses.c:4485
#9  0x0000620b4f739196 in simplify_function (funcid=41412, result_type=41028, result_typmod=-1, result_collid=result_collid@entry=0, input_collid=input_collid@entry=0, args_p=args_p@entry=0x7fff3cb4e8d0, funcvariadic=false, process_args=true,
    allow_non_const=true, context=0x7fff3cb4ead0) at clauses.c:4074
#10 0x0000620b4f7373ec in eval_const_expressions_mutator (node=0x620b50c4fd88, context=0x7fff3cb4ead0) at clauses.c:2573
#11 0x0000620b4f6a930b in expression_tree_mutator_impl (node=node@entry=0x620b50c4fdd8, mutator=mutator@entry=0x620b4f737112 <eval_const_expressions_mutator>, context=context@entry=0x7fff3cb4ead0) at nodeFuncs.c:3302
#12 0x0000620b4f737192 in eval_const_expressions_mutator (node=0x620b50c4fdd8, context=0x7fff3cb4ead0) at clauses.c:3693
#13 0x0000620b4f6a951d in expression_tree_mutator_impl (node=node@entry=0x620b50c4fe28, mutator=mutator@entry=0x620b4f737112 <eval_const_expressions_mutator>, context=context@entry=0x7fff3cb4ead0) at nodeFuncs.c:3389
#14 0x0000620b4f737192 in eval_const_expressions_mutator (node=0x620b50c4fe28, context=context@entry=0x7fff3cb4ead0) at clauses.c:3693
#15 0x0000620b4f7387b5 in eval_const_expressions (root=root@entry=0x620b50c4ff18, node=<optimized out>) at clauses.c:2249
#16 0x0000620b4f719660 in preprocess_expression (root=root@entry=0x620b50c4ff18, expr=<optimized out>, kind=kind@entry=1) at planner.c:1144
#17 0x0000620b4f7213e0 in subquery_planner (glob=glob@entry=0x620b50b7df80, parse=parse@entry=0x620b50b7e090, parent_root=parent_root@entry=0x0, hasRecursion=hasRecursion@entry=false, tuple_fraction=tuple_fraction@entry=0) at planner.c:811
#18 0x0000620b4f721fa9 in standard_planner (parse=0x620b50b7e090, query_string=<optimized out>, cursorOptions=2048, boundParams=<optimized out>) at planner.c:413
#19 0x0000620b4f72256b in planner (parse=parse@entry=0x620b50b7e090, query_string=query_string@entry=0x620b50b7d088 "SELECT agtype_build_map('null'::agtype, 1);", cursorOptions=cursorOptions@entry=2048, boundParams=boundParams@entry=0x0)
    at planner.c:281
#20 0x0000620b4f8019d5 in pg_plan_query (querytree=querytree@entry=0x620b50b7e090, query_string=query_string@entry=0x620b50b7d088 "SELECT agtype_build_map('null'::agtype, 1);", cursorOptions=cursorOptions@entry=2048, boundParams=boundParams@entry=0x0)
    at postgres.c:904
#21 0x0000620b4f801a8b in pg_plan_queries (querytrees=0x620b50c4fec8, query_string=query_string@entry=0x620b50b7d088 "SELECT agtype_build_map('null'::agtype, 1);", cursorOptions=cursorOptions@entry=2048, boundParams=boundParams@entry=0x0)
    at postgres.c:996
#22 0x0000620b4f801ef4 in exec_simple_query (query_string=query_string@entry=0x620b50b7d088 "SELECT agtype_build_map('null'::agtype, 1);") at postgres.c:1193
#23 0x0000620b4f803e2f in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4637
#24 0x0000620b4f765ede in BackendRun (port=port@entry=0x620b50ba6780) at postmaster.c:4464
#25 0x0000620b4f767ef6 in BackendStartup (port=port@entry=0x620b50ba6780) at postmaster.c:4192
#26 0x0000620b4f768094 in ServerLoop () at postmaster.c:1782
#27 0x0000620b4f7695d0 in PostmasterMain (argc=argc@entry=3, argv=argv@entry=0x620b50b37190) at postmaster.c:1466
#28 0x0000620b4f68e205 in main (argc=3, argv=0x620b50b37190) at main.c:198
```
Expected behavior:
Expected ERROR to be shown or sql query to be successfully executed

Best regards,
Egor Chindyaskin
Postgres Professional: http://postgrespro.com/

**Comment by jrgemignani** [comment]
@saygoodbyye Working on fix.

**Comment by jrgemignani** [comment]
@saygoodbyye PR #1957 resolves this issue and is being reviewed.

**Comment by saygoodbyye** [comment]
@jrgemignani, thank you, PR #1957, fixes this issue!
