### ISSUE TITLE
Crash on property access of node in same `MATCH`

### ISSUE THREAD

**Issue by DominicWuest** [apache/age#898]
I found a bug using my cypher fuzzer.

When running the following query against an empty database:
```
CREATE () WITH * MATCH (x{n0:x.n1}) RETURN 0
```

The postgres instance crashes and goes into recovery mode.

I encountered this issue when testing queries against the **apache/age:PG13_latest** docker image.

### Steps to reproduce

Spin up a local instance of **apache/age:PG13_latest**: `docker run -e POSTGRES_PASSWORD=123 --rm --name age apache/age:PG13_latest`

Get a shell in the docker container: `docker exec -it age /bin/bash`

Connect to postgres: `su postgres -c psql`

Run the following queries:
```psql
LOAD 'age';
-
SET search_path = ag_catalog, "$user", public;
-
SELECT create_graph('graph');
-
SELECT * FROM cypher('graph',$$
    CREATE () WITH * MATCH (x{n0:x.n1}) RETURN 0
$$) as (v agtype);
```

### Expected behavior
The query should run successfully

### Actual behavior
The database crashes

**Comment by DominicWuest** [comment]
`gdb` stacktrace

```
#0  __strnlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:74
#1  0x0000557661a30d4f in pnstrdup ()
#2  0x00007f158ae5b020 in fill_agtype_value (
    container=container@entry=0x557662af4134, index=index@entry=0, 
    base_addr=base_addr@entry=0x5576a2af4134 <error: Cannot access memory at address 0x5576a2af4134>, offset=<optimized out>, 
    result=result@entry=0x557662af42a8)
    at src/backend/utils/adt/agtype_util.c:563
#3  0x00007f158ae5b30b in get_ith_agtype_value_from_container (
    container=container@entry=0x557662af4134, i=i@entry=0)
    at src/backend/utils/adt/agtype_util.c:525
#4  0x00007f158ae4ec4f in agtype_access_operator (fcinfo=0x557662afe178)
    at src/backend/utils/adt/agtype.c:3429
#5  0x0000557661783b02 in ?? ()
#6  0x0000557661790492 in ExecScan ()
#7  0x00005576617b1775 in ?? ()
#8  0x000055766178742d in standard_ExecutorRun ()
#9  0x00005576618f332b in ?? ()
#10 0x00005576618f48a8 in PortalRun ()
#11 0x00005576618f0301 in ?? ()
#12 0x00005576618f2454 in PostgresMain ()
#13 0x00005576618794a5 in ?? ()
#14 0x000055766187a3f4 in PostmasterMain ()
#15 0x00005576615fc046 in main ()
```
